suburbs_data = [
    "clayton",
    "mount waverley",
    "glen waverley",
    "mulgrave",
    "clayton south",
    "burwood east",
    "vermont",
    "vermont south",
    "wheelers hill",
    "chadstone",
    "oakleigh",
    "doncaster",
    "doncaster east",
    "wantirna",
    "wantirna south",
    "carnegie",
    "keysborough",
    "ringwood",
    "mitcham",
    "forest hill",
    "nunawading",
    "blackburn",
    "blackburn south",
    "scoresby",
    "rowville",
    "noble park",
    "cheltenham",
    "point cook",
    "croydon north",
    "croydon hills",
    "glen iris",
    "caulfield",
    "caulfield south",
    "balwyn",
    "bentleigh east",
    "bentleigh",
    "box hill",
    "burwood"
]

